### ISSUE TITLE
No need for the staticCheck

### ISSUE THREAD

**Issue by speekha** [igorwojda/android-showcase#24]
Do you really need the staticCheck task in your gradle conf?
Couldn't you just do "./gradlew check" to perform all the tasks related to tests and deteckt/ktlint/etc.?

**Comment by igorwojda** [comment]
This is interesting. I did some investigation on `check` task.

1. In general, it looks like something that I may want to use, however, for now, it looks like it is affected by `ktlint-gradle` plugin issue (https://github.com/JLLeitschuh/ktlint-gradle/issues/266), so I have to wait for it to be fixed (otherwise ktlint settings are ignored and ktlint checks are failing).


2. I noticed that `check` task runs all the checks twice (for `Debug` and `Release`), so I am guessing tests will run twice 🤔 Run to list tasks: `./gradlew check --dry-run | grep test`. Result:
```
:feature_album:testDebugUnitTest
:feature_album:testReleaseUnitTest
:feature_album:test
...
```

**Comment by speekha** [comment]
Indeed, "gradle check" will test all build types, just like a "gradle test" would (in some cases, that could actually be useful if you have slight differences between the two variants, like obfuscation).
Thanks for the answer.

**Comment by igorwojda** [comment]
Thx for the feedback.

BTW this makes me think that my `static check` task could be re-named to `checkDebug` and do exactly what `check` does, but only for all the Debug tasks (filtering our Release tasks). I will investigate it further when ktlint-gradle bug will be fixed
