### ISSUE TITLE
Db Support

### ISSUE THREAD

**Issue by ronnyremesnik** [igorwojda/android-showcase#47]
Hi @igorwojda  Thanks for great sample project.
Did you plan to add also support for Db layer ?
if not in the near future, can you please help design what will be the best approach to add db representation, in order to be accesses from all the modules.
Thanks, 
Ronny.

**Comment by igorwojda** [comment]
Yes, I plan to add a database at some point.
My approach would be to have separate db (SQL db file) per each module because this approach provides appropriate level of the feature separation.

See
https://github.com/googlesamples/android-architecture-components/issues/274

**Comment by batyrf** [comment]
I'd like to work on this

**Comment by igorwojda** [comment]
Go for it

**Comment by gugahaker** [comment]
I don't quite understand how would feature_favourite work with separate database. It would contain a list of albums, same as feature_album, but only a subset that user selected. So data model classes and domain model classes should be the same. But if there are two separate databases, I don't see how would a user (another entity shared between features) favourite an album in feature_albums so that it shows up in feature_favourite since those two features don't know about each other and have separate databases.
I hope question makes sense.

**Comment by igorwojda** [comment]
Good point indeed @gugahaker. I need to rethink it and take a closer look.

For now DB support was implemented by this PR
https://github.com/igorwojda/android-showcase/pull/149
