### ISSUE TITLE
how to notify view model of changing bluetooth connection

### ISSUE THREAD

**Issue by haniyehkhaksar** [igorwojda/android-showcase#65]
how we can notify view model  of any changes of sensors of android device. I want to find the best practice of notifying changes in clean architecture way. I think about bus event and broadcast receiver.

**Comment by igorwojda** [comment]
Not really project related question, but from architecture perspective there are few options.

I am not a big fan of `event bus` because overtime it may grow out of control (hard to track event flow across the whole app). You could have dedicated event buss per event type (`BluettothConnectoionStateEventBus`, `InternetAvalabilityEventBus`, etc.), but it is still quite easy to violate CA dependency rule (mess up the layer separation). 

Since this is not typical UseCase that can be `executed` and return the single result we can expose this data directly from repository that is injected into ViewModel (instead of UseCase as we would do normally access repository). The main difference here is that repository method would expose data instead stream instead of single data eg.:

```
// method in the repository
fun observerBluetoothSensorData(): LiveData<BluetoothSensorDomainModel>
```

 Depending on the project tech-stack we could use `LiveData`, `Kotlin Flow` or `RxJava` to represent the data stream.

**Comment by haniyehkhaksar** [comment]
Thank you, I thought that there is maybe a way that I don't know. your response helps me to move on.
